set -g prefix C-a
unbind C-b
bind C-a send-prefix

# 开启鼠标控制
set -g mouse on

# 颜色
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# 窗口编号从 1 开始
set -g base-index 1
setw -g pane-base-index 1
